In [16]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
df = pd.read_csv("C:/Users/samya/Downloads/data.csv")
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [19]:
df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [20]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [21]:
df['age'].max()

np.int64(90)

In [22]:
df['age'].min()

np.int64(17)

In [23]:
df['income'].min()

'<=50K'

In [24]:
df['income'].max()

'>50K'

In [25]:
df.groupby(['income','age']).max()

                   workclass   fnlwgt     education  educational-num  \
income age
<=50K  17          State-gov   806316  Some-college               10
       18          State-gov   761006  Some-college               14
       19        Without-pay  1047822  Some-college               13
       20          State-gov   745817  Some-college               14
       21        Without-pay   811615  Some-college               14
...                      ...      ...           ...              ...
>50K   83       Self-emp-inc   240150     Bachelors               13
       84       Self-emp-inc   172907  Some-college               10
       85       Self-emp-inc   155981     Bachelors               13
       88   Self-emp-not-inc   263569          11th                7
       90   Self-emp-not-inc   313986   Prof-school               15

                marital-status        occupation   relationship   race gender  \
income age
<=50K  17              Widowed  Transport-moving      Unmarried  White   Male
       18              Widowed  Transport-moving           Wife  White   Male
       19            Separated  Transport-moving           Wife  White   Male
       20            Separated  Transport-moving           Wife  White   Male
       21              Widowed  Transport-moving           Wife  White   Male
...                        ...               ...            ...    ...    ...
>50K   83   Married-civ-spouse   Farming-fishing        Husband  White   Male
       84   Married-civ-spouse             Sales        Husband  White   Male
       85              Widowed   Exec-managerial  Not-in-family  White   Male
       88   Married-civ-spouse   Farming-fishing        Husband  White   Male
       90        Never-married             Sales           Wife  White   Male

            capital-gain  capital-loss  hours-per-week native-country
income age
<=50K  17          34095          1721              50  United-States
       18          34095          1721              72  United-States
       19          34095          2129              99     Yugoslavia
       20          34095          2258              84     Yugoslavia
       21           4865          2603              98        Vietnam
...                  ...           ...             ...            ...
>50K   83          20051          2392              55  United-States
       84              0             0              35  United-States
       85              0             0              40  United-States
       88           6418             0              40  United-States
       90          20051          1825              72  United-States

[142 rows x 13 columns]

In [26]:
df.groupby(['income','age']).min()

                   workclass  fnlwgt     education  educational-num  \
income age
<=50K  17                  ?   19752          10th                3
       18                  ?   20057          10th                3
       19                  ?   20469          10th                1
       20                  ?   19410          10th                1
       21                  ?   20728          10th                1
...                      ...     ...           ...              ...
>50K   83       Self-emp-inc  153183          10th                6
       84       Self-emp-inc  172907  Some-college               10
       85       Self-emp-inc  155981     Bachelors               13
       88   Self-emp-not-inc  263569          11th                7
       90                  ?   46786    Assoc-acdm                9

                marital-status       occupation   relationship  \
income age
<=50K  17   Married-civ-spouse                ?        Husband
       18             Divorced                ?        Husband
       19             Divorced                ?        Husband
       20             Divorced                ?        Husband
       21             Divorced                ?        Husband
...                        ...              ...            ...
>50K   83   Married-civ-spouse  Exec-managerial        Husband
       84   Married-civ-spouse            Sales        Husband
       85              Widowed  Exec-managerial  Not-in-family
       88   Married-civ-spouse  Farming-fishing        Husband
       90   Married-civ-spouse                ?        Husband

                          race  gender  capital-gain  capital-loss  \
income age
<=50K  17   Amer-Indian-Eskimo  Female             0             0
       18   Amer-Indian-Eskimo  Female             0             0
       19   Amer-Indian-Eskimo  Female             0             0
       20   Amer-Indian-Eskimo  Female             0             0
       21   Amer-Indian-Eskimo  Female             0             0
...                        ...     ...           ...           ...
>50K   83                White    Male             0             0
       84                White    Male             0             0
       85                White    Male             0             0
       88                White    Male          6418             0
       90                Black  Female             0             0

            hours-per-week native-country
income age
<=50K  17                4              ?
       18                2              ?
       19                2              ?
       20                2              ?
       21                1              ?
...                    ...            ...
>50K   83               50  United-States
       84               35  United-States
       85               40  United-States
       88               40  United-States
       90               15        Ecuador

[142 rows x 13 columns]

In [27]:
df.groupby('income')['age'].mean()

income
<=50K    36.872184
>50K     44.275178
Name: age, dtype: float64

In [28]:
df.groupby('income')['age'].median()

income
<=50K    34.0
>50K     43.0
Name: age, dtype: float64

In [29]:
df.groupby('income')['age'].std()

income
<=50K    14.104118
>50K     10.558983
Name: age, dtype: float64

In [30]:
df = sns.load_dataset('iris')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [34]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [35]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [37]:
df.groupby('species').count()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

In [42]:
setosa = df[df['species']=='setosa']
versicolor = df[df['species']== 'versicolor']	
virginica = df[df['species'] == 'virginica']

In [39]:
setosa

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [43]:
versicolor

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

In [44]:
virginica

     sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
106           4.9          2.5           4.5          1.7  virginica
107           7.3          2.9           6.3          1.8  virginica
108           6.7          2.5           5.8          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
110           6.5          3.2           5.1          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
112           6.8          3.0           5.5          2.1  virginica
113           5.7          2.5           5.0          2.0  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
116           6.5          3.0           5.5          1.8  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [46]:
setosa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  50 non-null     float64
 1   sepal_width   50 non-null     float64
 2   petal_length  50 non-null     float64
 3   petal_width   50 non-null     float64
 4   species       50 non-null     object
dtypes: float64(4), object(1)
memory usage: 2.3+ KB

In [47]:
versicolor.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 50 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  50 non-null     float64
 1   sepal_width   50 non-null     float64
 2   petal_length  50 non-null     float64
 3   petal_width   50 non-null     float64
 4   species       50 non-null     object
dtypes: float64(4), object(1)
memory usage: 2.3+ KB

In [48]:
virginica.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 100 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  50 non-null     float64
 1   sepal_width   50 non-null     float64
 2   petal_length  50 non-null     float64
 3   petal_width   50 non-null     float64
 4   species       50 non-null     object
dtypes: float64(4), object(1)
memory usage: 2.3+ KB

In [60]:
def information(spd,spn):
    n_col = ['sepal_length','sepal_width','petal_length','petal_width']
    print(f'------------------------------{spn}-----------------------')
    print(f'mean: \n{spd[n_col].mean()}')
    print('-----------------------------------------------------------')
    print(f'median: \n{spd[n_col].median()}')
    print('-----------------------------------------------------------')
    print(f'25%: \n{spd[n_col].quantile(0.25)}')
    print('-----------------------------------------------------------')
    print(f'75%: \n{spd[n_col].quantile(0.75)}')
    print('-----------------------------------------------------------')
    print(f'std: \n{spd[n_col].std()}')
    print('-----------------------------------------------------------')

In [61]:
information(setosa,'setosa')

------------------------------setosa-----------------------
mean:
sepal_length    5.006
sepal_width     3.428
petal_length    1.462
petal_width     0.246
dtype: float64
-----------------------------------------------------------
median:
sepal_length    5.0
sepal_width     3.4
petal_length    1.5
petal_width     0.2
dtype: float64
-----------------------------------------------------------
25%:
sepal_length    4.8
sepal_width     3.2
petal_length    1.4
petal_width     0.2
Name: 0.25, dtype: float64
-----------------------------------------------------------
75%:
sepal_length    5.200
sepal_width     3.675
petal_length    1.575
petal_width     0.300
Name: 0.75, dtype: float64
-----------------------------------------------------------
std:
sepal_length    0.352490
sepal_width     0.379064
petal_length    0.173664
petal_width     0.105386
dtype: float64
-----------------------------------------------------------

In [62]:
information(versicolor,'versicolor')

------------------------------versicolor-----------------------
mean:
sepal_length    5.936
sepal_width     2.770
petal_length    4.260
petal_width     1.326
dtype: float64
-----------------------------------------------------------
median:
sepal_length    5.90
sepal_width     2.80
petal_length    4.35
petal_width     1.30
dtype: float64
-----------------------------------------------------------
25%:
sepal_length    5.600
sepal_width     2.525
petal_length    4.000
petal_width     1.200
Name: 0.25, dtype: float64
-----------------------------------------------------------
75%:
sepal_length    6.3
sepal_width     3.0
petal_length    4.6
petal_width     1.5
Name: 0.75, dtype: float64
-----------------------------------------------------------
std:
sepal_length    0.516171
sepal_width     0.313798
petal_length    0.469911
petal_width     0.197753
dtype: float64
-----------------------------------------------------------

In [63]:
information(virginica,'virginica')

------------------------------virginica-----------------------
mean:
sepal_length    6.588
sepal_width     2.974
petal_length    5.552
petal_width     2.026
dtype: float64
-----------------------------------------------------------
median:
sepal_length    6.50
sepal_width     3.00
petal_length    5.55
petal_width     2.00
dtype: float64
-----------------------------------------------------------
25%:
sepal_length    6.225
sepal_width     2.800
petal_length    5.100
petal_width     1.800
Name: 0.25, dtype: float64
-----------------------------------------------------------
75%:
sepal_length    6.900
sepal_width     3.175
petal_length    5.875
petal_width     2.300
Name: 0.75, dtype: float64
-----------------------------------------------------------
std:
sepal_length    0.635880
sepal_width     0.322497
petal_length    0.551895
petal_width     0.274650
dtype: float64
-----------------------------------------------------------